apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
    - stage: test
      autoPromotionEnabled: true
    - stage: prod
      autoPromotionEnabled: false