apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
  annotations:
    kargo.akuity.io/color: violet
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: kargo-demo
      sources:
        direct: false
        stages:
          - test
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/procinger/kargo-demo.git
            checkout:
              - fromFreight: true
                path: ./src
              - branch: stage/prod
                path: ./out
                create: true
        - uses: git-clear
          config:
            path: ./out
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/kustomize/base
            images:
              - image: ghcr.io/procinger/kargo-demo
        - uses: kustomize-build
          config:
            path: ./src/kustomize/overlays/prod
            outPath: ./out/kustomize/stages/prod/manifests.yaml
        - uses: git-commit
          as: commit
          config:
            path: ./out
            message: Upcoming Production Release
        - uses: git-push
          as: push
          config:
            path: ./out
            generateTargetBranch: true
        - uses: git-open-pr
          as: open-pr
          config:
            repoURL: https://github.com/procinger/kargo-demo.git
            provider: github
            createTargetBranch: true
            sourceBranchFromStep: push
            targetBranch: stage/prod
        - uses: git-wait-for-pr
          as: wait-for-pr
          config:
            repoURL: https://github.com/procinger/kargo-demo.git
            prNumberFromStep: open-pr
        - uses: argocd-update
          config:
            apps:
              - name: kargo-demo-prod
                namespace: argo-cd
                sources:
                  - repoURL: https://github.com/procinger/kargo-demo.git
                    desiredCommitFromStep: wait-for-pr
