apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  interval: "10m0s"
  subscriptions:
    - image:
        repoURL: ghcr.io/procinger/kargo-demo
        semverConstraint: ^1.0.0
        discoveryLimit: 5
    - git:
        repoURL: https://github.com/procinger/kargo-demo.git
        branch: main
