apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: http-smoke-test-analysis
spec:
  metrics:
  - count: 5
    failureLimit: 0
    interval: 5s
    name: http-smoke-test-metric
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - command:
                - /bin/sh
                - -c
                - |
                  (curl --insecure -H "canary: true" -L -o /dev/null -s -w %{http_code} \
                  https://lab.hukmedia.de | grep ${HTTP_SUCCESS_CODE}) || (echo "http test failed. expected ${HTTP_SUCCESS_CODE}"; exit 1)
                env:
                - name: HTTP_SUCCESS_CODE
                  value: "200"
                image: curlimages/curl:latest
                imagePullPolicy: IfNotPresent
                name: http-smoke-test-job
              restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
spec:
  ports:
  - name: kargo-demo
    port: 80
  selector:
    app: kargo-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kargo-demo
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: ghcr.io/procinger/kargo-demo:1.10.1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ -f /run/nginx.pid ] && test -f /proc/$(cat /run/nginx.pid)/exe'
        name: kargo-demo
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
      imagePullSecrets:
      - name: gitlab-registry-credentials
