apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
---
apiVersion: v1
kind: Service
metadata:
  name: kargo-demo
spec:
  ports:
  - name: kargo-demo
    port: 80
  selector:
    app: kargo-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kargo-demo
  name: kargo-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kargo-demo
  template:
    metadata:
      labels:
        app: kargo-demo
    spec:
      containers:
      - image: ghcr.io/procinger/kargo-demo:1.23.1
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - '[ -f /run/nginx.pid ] && test -f /proc/$(cat /run/nginx.pid)/exe'
        name: kargo-demo
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
      imagePullSecrets:
      - name: ghcr-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: curl-app
  name: curl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-app
  template:
    metadata:
      labels:
        app: curl-app
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - |
          while true
          do
            curl --insecure -L -o /dev/null -s -w %{http_code} http://kargo-demo
            sleep 5
          done
        image: docker.io/curlimages/curl:8.11.0
        name: curl-app
