FROM docker.io/nginx:stable-alpine3.20@sha256:d6f8c6b38edf2b7c6619718ad7a00caa4ed4741d12ce12550333a28d2b52dc89

LABEL org.opencontainers.image.source="https://github.com/procinger/kargo-demo"

COPY index.html /usr/share/nginx/html/index.html